
language: node_js

node_js: 
  - "stable"

install:
  - npm install
  - cd client && npm install && cd ..
  
services: mongodb

before_script:
  - npm install -g express
  - npm install -g express-generator
  - npm install -g @angular/cli

script:
  - cd client && ng build

cache:
  directories:
    - "node_modules"
